### ISSUE TITLE
Incorrect setup when resampler is disabled

### ISSUE THREAD

**Issue by gavv** [roc-project/roc#133]
Bad:

```
$ ./roc-recv -vv -s :10001 -r :10002 --resampling=no
...
latency monitor: initializing: target_latency=8640 in_rate=44100 out_rate=48000
```

Good:

```
$ ./roc-recv -vv -s :10001 -r :10002 --resampling=no --rate 44100
...
latency monitor: initializing: target_latency=8640 in_rate=44100 out_rate=44100
```

The problem is that roc-recv detects 48k card and sets output rate to 48k, so that SoX/PulseAudio resampling is disabled. However, our resampler is disabled as well, and we send 44100 Hz samples to the sound card.

**Comment by dshil** [comment]
I suppose that you mean `no-resampling` option.

**Comment by gavv** [comment]
Yeah, I've renamed `--resampling=no` to `--no-resampling` recently.

**Comment by dshil** [comment]
@gavv, I've made a small fix: https://github.com/roc-project/roc/pull/142.

I think that it doesn't solve the whole problem because we just don't create a session and for the next packet we'll try to create it again.

I suppose, that we should have some kind of sessions that should be marked as `not restarted`, we just need to inform user once about the problem and drop all packets for the corresponding session.

**Comment by gavv** [comment]
Well, this is a useful check, but what we really need is to force SoX Player to use pipeline::DefaultSampleRate (44100) when resampling is disabled, instead of allowing it to autodetect rate. This will enable resampling in PulseAudio.

**Comment by gavv** [comment]
Works now.
