### ISSUE TITLE
Scons-Script Which extension for windows

### ISSUE THREAD

**Issue by philippk80** [roc-project/roc#143]
On windows it seems like os.access() returning always false.
This leeds to .Which() returning an empty array.

Maybe here it is needed to make a fallback with a try catch or is there a better solution to check if files are executable? 

(Tested on Powershell with and without administration permissions)

**Comment by philippk80** [comment]
Or maybe even use https://docs.python.org/dev/library/shutil.html#shutil.which

**Comment by gavv** [comment]
> Or maybe even use https://docs.python.org/dev/library/shutil.html#shutil.which

Unfortunately, shutil.which is not available for Python 2.7, which is still used for SCons in many distros.

> On windows it seems like os.access() returning always false.

It's strange. After looking at the [source code](https://github.com/python/cpython/blob/master/Modules/posixmodule.c#L2559), I'd rather expect it always return true. Probably your executable is read-only?

Anyway, it seems that X_OK is not really checked on Windows.

There are two os.access calls in env.Which: first we check `p`, then we check `p + e`, where `e` is an extension from PATHEXT variable, which is AFAIK Windows-specific.

So, since the first check would work on unix platforms, and the second one on Windows, and X_OK doesn't work on Windows as expected, I think we can just change X_OK in the second check to F_OK.

**Comment by philippk80** [comment]
> Or maybe even use https://docs.python.org/dev/library/shutil.html#shutil.which
Okay. It makes sense to achieve a wide compatibility.

Sadly shutil.which works on windows like a charm. 

> It's strange. After looking at the source code, I'd rather expect it always return true. Probably your executable is read-only?

I already checked this. All users have the permission on my mashine. But maybe I will check this on another to verfiy. Windows 10 was used here.

F_OK doesn't work too. Maybe we have another issue causing this and we don't think about it.

**Comment by gavv** [comment]
> shutil.which works on windows like a charm.

Well, then you could check [its implementation](https://github.com/python/cpython/blob/master/Lib/shutil.py#L1109) and see what's wrong with env.Which.

**Comment by philippk80** [comment]
**it seems like this is causing the problem:**
[Source Line 83](https://github.com/roc-project/roc/blob/aded3c18ddecd819e0b3978978a5cf9a3d3306a1/site_scons/site_tools/roc/helpers.py#L83)

today
` exts = filter(None, getenv('PATHEXT', '').split(os.pathsep))`

working on windows:
` exts = getenv('PATHEXT', '').split(os.pathsep))`

**Comment by gavv** [comment]
Hi, sorry for delay.

Three questions then:

1. What does `getenv('PATHEXT', '').split(os.pathsep)` return?
2. What does `filter(None, getenv('PATHEXT', '').split(os.pathsep))` return?
3. What is the full name of the executable that is found after your fix?

**Comment by philippk80** [comment]
Sorry for the long silence.

I can test the points and give you the detailed information at another time.

Just for information to give an intermediate result:

When I print out filter() I will get an address I think and not the array needed. This is why it works without the filter statement. Without it exts will set to an array with the desired data.

**Comment by gavv** [comment]
We now use shutil.which() if it is available and fallback to our own implementation otherwise. I hope this will fix this issue. This is pushed to develop branch.

Closing this, feel free to reopen if necessary.
