### ISSUE TITLE
fcntl alterantive for windows

### ISSUE THREAD

**Issue by philippk80** [roc-project/roc#144]
Any suggestions what to use?

Maybe we could use https://pypi.python.org/pypi/portalocker
...but there is a windows bug which is only fixed in dev-branch since may
Another one I found is:
https://pypi.python.org/pypi/filelock

**Comment by gavv** [comment]
If possible, I'd like to avoid adding dependencies on Python modules that are not in standard library (currently, the user only needs to install Python and SCons and no additional modules).

It seems that the standard library provides access to Windows file locking API, probably we can just use it: https://docs.python.org/2/library/msvcrt.html#msvcrt.locking

**Comment by gavv** [comment]
I've fixed clangdb script so it first tries to use `fcntl` module if it's available (linux, unix, macos) and otherwise tries `msvcrt` module (windows).

This is pushed to the develop branch.

(Note: I didn't start working on the windows port so far; just wanted to resolve this issue because it was quite straightforward).

Closing this, feel free to reopen if necessary.
